### ISSUE TITLE
ORA instruction flags

### ISSUE THREAD

**Issue by kelaroo** [FunIsDangerous/8085_emulator#4]
The ORA instruction does not update the flags.

For example:
both
&nbsp;MVI A,00h
&nbsp;ORA A
and
&nbsp;MVI A,01h
&nbsp;ORA A
will have Z=0(even though in the first case the value in A after ORA is 00h. This is true with any other register.

Looking through the source code, it seems that ANA updates the flags, but ORA just stores the bitwise OR.

**Comment by FanisDeligiannis** [comment]
Seems like an oversight on my part.
Same thing happened for ORI, not just ORA. 

Fixed as of b3fc131b0125c3babca6a09357eabe0dabacd78a, thank you.
