### ISSUE TITLE
Wrong Z flag with ANA instruction

### ISSUE THREAD

**Issue by kelaroo** [FunIsDangerous/8085_emulator#5]
The Z flag after the ANA instruction is opposite to what it should be:

For example:
&nbsp; MVI A,00h
&nbsp; MVI B,00h
&nbsp; ANA B
will set Z to 0 (even though the value in A is 00h) and
&nbsp; MVI A,01h
&nbsp; MVI B,01h
&nbsp; ANA B
will set Z to 1 (even though the value in A is 01h).

This seems to be due to the fact that in _CPUinstructions.cpp_, the function **void And(uint8_t)** (that is called by ANAA, ANAB, etc.) , sets Z to 1 when result is different to 0, which should set it to 1 when equal to 0.

I am referring to this in the source code, inside the And function:
`
cpu->SetFlags(
            (result & 0b10000000) > 0,
            result != 0,
            0,
            !(bits_in(*(uint8_t*)&result) % 2),
            0
        );
`
which should be:
`cpu->SetFlags(
            (result & 0b10000000) > 0,
            result == 0,
            0,
            !(bits_in(*(uint8_t*)&result) % 2),
            0
        );`

**Comment by FanisDeligiannis** [comment]
I apparently had that logic backwards. It was wrong in some other places too.

JZ/JNZ was working properly because I had the logic backwards there too. Fixed (hopefully) everywhere as of cb074cb3eaee59bbe0c524621299c4a25f196ad9, thank you
