### ISSUE TITLE
Wrong color on labels containing numbers

### ISSUE THREAD

**Issue by purpl3F0x** [FunIsDangerous/8085_emulator#8]
There is a visual issue with labels containing numbers as the numbers get highlighted as if they were a regular number in code.

![image](https://user-images.githubusercontent.com/16735391/230769196-542cf7a8-284c-4d40-81f9-4d8f34411302.png)
 

P.S. Assembles as expected, no issues

**Comment by FanisDeligiannis** [comment]
Fixed as of 735050f113b7410d24b90a95732b0f8f07ad5430
