### ISSUE TITLE
Compare Operation should be with unsigned numbers

### ISSUE THREAD

**Issue by purpl3F0x** [FunIsDangerous/8085_emulator#9]
I stugle to find any specific info on this, but  - I think - the comparison is done by subtracting the unsigned numbers - not signed as it is.
GNUSim8085 seem to do it that way and https://www.sim8085.com/.

**Comment by FanisDeligiannis** [comment]
Fixed as of 735050f113b7410d24b90a95732b0f8f07ad5430
